set nocompatible

call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

nohlsearch

set number
set ruler

set encoding=utf-8
syntax  on

" whitespaces
set wrap
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set list listchars=tab:\ \ ,trail:·

set hlsearch
set incsearch
set ignorecase
set smartcase

" Tab completion
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc,*.class,.svn,vendor/gems/*

set laststatus=2

map qa  :NERDTreeToggle<CR>

if has("autocmd")
  autocmd BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif
endif

function s:setupWrapping()
  set wrap
  set wrapmargin=2
  set textwidth=72
endfunction

" make uses real tabs
autocmd FileType make set noexpandtab

" Thorfile, Rakefile, Vagrantfile and Gemfile are Ruby
autocmd BufRead,BufNewFile {Gemfile,Rakefile,Vagrantfile,Thorfile,config.ru} set ft=ruby

" add json syntax highlighting
autocmd BufNewFile,BufRead *.json set ft=javascript

" md, markdown, and mk are markdown and define buffer-local preview
autocmd BufRead,BufNewFile *.{md,markdown,mdown,mkd,mkdn} call s:setupWrapping()

autocmd FileType html,htmldjango,jinjahtml,eruby,mako let b:closetag_html_style=1
autocmd FileType html,xhtml,xml,htmldjango,jinjahtml,eruby,mako source ~/.vim/bundle/closetag/plugin/closetag.vim

" make Python follow PEP8 ( http://www.python.org/dev/peps/pep-0008/ )
autocmd FileType python set softtabstop=4 tabstop=4 shiftwidth=4 textwidth=79

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" load the plugin and indent settings for the detected filetype
filetype plugin indent on

" Enable syntastic syntax checking
let g:syntastic_enable_signs=1
let g:syntastic_quiet_warnings=1

let g:tagbar_usearrows = 1
nnoremap qw :TagbarToggle<CR>


" Directories for swp files
set backupdir=~/.cache/vim
set directory=~/.cache/vim

set showcmd

" % to bounce from do to end etc.
runtime! macros/matchit.vim

colorscheme desert

autocmd BufEnter *.hs compiler ghc
autocmd BufEnter *.hs GHCReload
let g:ghc="/usr/bin/ghc"
let g:haddoc_docdir="/usr/share/doc/ghc/html/"
let g:haddock_browser="/usr/bin/arora"
