set nocompatible

if has ('vim_starting')
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#rc(expand('~/.vim/bundle/'))

runtime! bundles.vim

" delegate configuration to files in config/
runtime! config/**/*.vim
