nnoremap <Leader>th :setlocal hlsearch!<cr>
nnoremap <Leader>tl :setlocal list!<cr>
nnoremap <Leader>tn :setlocal number!<cr>
nnoremap <Leader>tN :setlocal relativenumber!<cr>
nnoremap <Leader>tp :setlocal paste!<cr>
nnoremap <Leader>ts :setlocal spell!<cr>
nnoremap <Leader>tz :setlocal foldenable!<cr>
nnoremap <Leader>tc :setlocal cursorcolumn!<cr>
nnoremap <Leader>tC :setlocal cursorline!<cr>
