nnoremap <Leader>th :setlocal hlsearch!<Enter>
nnoremap <Leader>tl :setlocal list!<Enter>
nnoremap <Leader>tn :setlocal number!<Enter>
nnoremap <Leader>tN :setlocal relativenumber!<Enter>
nnoremap <Leader>tp :setlocal paste!<Enter>
nnoremap <Leader>ts :setlocal spell!<Enter>
nnoremap <Leader>tz :setlocal foldenable!<Enter>
nnoremap <Leader>tc :setlocal cursorcolumn!<Enter>
nnoremap <Leader>tC :setlocal cursorline!<Enter>
